### ISSUE TITLE
GraphQL Storefront - Checkout updates v2 - Stripe saved card requirements 

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/design#46]
Review & update payment flows for guest and signed-in checkout for compliance with Stripe's requirements. 

https://stripe.com/docs/saving-cards

https://stripe.com/docs/stripe-js

**Comment by rymorgan** [comment]
Here's an example of stripe implementation. 
<img width="382" alt="screen shot 2018-06-18 at 10 49 26 am" src="https://user-images.githubusercontent.com/20409254/41567719-83a9305c-7316-11e8-9a57-29ea32686f7f.png">
